import {
  ColumnType,
  Generated,
  Insertable,
  JSONColumnType,
  Selectable,
  Updateable,
} from "kysely";

// Define the database structure
export interface Database {
  user: UserTable;
  user_session: UserSessionTable;
  role: RoleTable;
  permission: PermissionTable;
  role_permission: RolePermissionTable;
  user_role: UserRoleTable;
  address: AddressTable;
  wishlist: UserWishlistTable;
  product: ProductTable;
  brand: BrandTable;
  manufacturer: ManufacturerTable;
  variation: ProductVariationTable;
  product_variation: ProductVariationMappingTable;
  product_image: ProductImagesTable;
  category: CategoryTable;
  tag: ProductTagTable;
  product_tag: ProductTagMappingTable;
  discount: DiscountTable;
  warranty: WarrantyTable;
  product_review: ProductReviewTable;
  shopping_session: ShoppingSessionTable;
  cart_item: CartItemTable;
  order: OrderTable;
  order_item: OrderItemTable;
  payment: PaymentTable;
  shipping: ShippingTable;
  shipping_address: ShippingAddressTable;
  refund: RefundTable;
  verification_request: VerificationRequestTable;
}

// This interface describes the `user` table to Kysely. Table
// interfaces should only be used in the `Database` type above
// and never as a result type of a query!. See the `User`,
// `NewUser` and `UserUpdate` types below.
export interface UserTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;
  phone: string;
  phone_verified: boolean;
  // If the column is nullable in the database, make its type nullable.
  // Don't use optional properties. Optionality is always determined
  // automatically by Kysely.
  email: string | null;
  email_verified: boolean;
  username: string | null;
  first_name: string | null;
  last_name: string | null;
  avatar: string | null;
  otp_verified: boolean;
  // You can specify a different type for each operation (select, insert and
  // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
  // wrapper. Here we define a column `created_at` that is selected as
  // a `Date`, can optionally be provided as a `string` in inserts and
  // can never be updated:
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
  // You can specify JSON columns using the `JSONColumnType` wrapper.
  // It is a shorthand for `ColumnType<T, string, string>`, where T
  // is the type of the JSON object/array retrieved from the database,
  // and the insert and update types are always `string` since you're
  // always stringifying insert/update values.
}

// User session table interface
export interface UserSessionTable {
  id: string;
  user_id: number;
  expires_at: Date;
  created_at: ColumnType<Date, string | undefined, never>;
}

// Roles table interface
export interface RoleTable {
  id: Generated<number>;
  name: string; // Role name, e.g., "Admin", "Customer"
  description: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Permissions table interface
export interface PermissionTable {
  id: Generated<number>;
  name: string; // Permission name, e.g., "manage_products", "view_orders"
  description: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Role-Permission mapping table interface
export interface RolePermissionTable {
  id: Generated<number>;
  role_id: number;
  permission_id: number;
  created_at: ColumnType<Date, string | undefined, never>;
}

// User-Role mapping table interface
export interface UserRoleTable {
  id: Generated<number>;
  user_id: number;
  role_id: number;
  created_at: ColumnType<Date, string | undefined, never>;
}

// Address table interface
export interface AddressTable {
  id: Generated<number>;
  user_id: number;
  address_line1: string;
  address_line2: string | null;
  city: string;
  state: string;
  postal_code: string;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Wishlist table interface
export interface UserWishlistTable {
  id: Generated<number>;
  user_id: number;
  product_id: number;
  created_at: ColumnType<Date, string | undefined, never>;
}
// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
//
// Most of the time you should trust the type inference and not use explicit
// types at all. These types can be useful when typing function arguments.
export type User = Selectable<UserTable>;
export type NewUser = Insertable<UserTable>;
export type UserUpdate = Updateable<UserTable>;
export type UserSession = Selectable<UserSessionTable>;
export type NewUserSession = Insertable<UserSessionTable>;
export type UserSessionUpdate = Updateable<UserSessionTable>;
export type Role = Selectable<RoleTable>;
export type NewRole = Insertable<RoleTable>;
export type RoleUpdate = Updateable<RoleTable>;
export type Permission = Selectable<PermissionTable>;
export type NewPermission = Insertable<PermissionTable>;
export type PermissionUpdate = Updateable<PermissionTable>;
export type RolePermission = Selectable<RolePermissionTable>;
export type NewRolePermission = Insertable<RolePermissionTable>;
export type RolePermissionUpdate = Updateable<RolePermissionTable>;
export type UserRole = Selectable<UserRoleTable>;
export type NewUserRole = Insertable<UserRoleTable>;
export type UserRoleUpdate = Updateable<UserRoleTable>;
export type Address = Selectable<AddressTable>;
export type NewAddress = Insertable<AddressTable>;
export type AddressUpdate = Updateable<AddressTable>;
export type UserWishlist = Selectable<UserWishlistTable>;
export type NewUserWishlist = Insertable<UserWishlistTable>;
export type UserWishlistUpdate = Updateable<UserWishlistTable>;

// Product table interface
export interface ProductTable {
  id: Generated<number>;
  name: string;
  description: string;
  thumbnail: string | null;
  price: number;
  sku: string;
  stock: number;
  min_order_quantity: number | null;
  max_order_quantity: number | null;
  weight: number | null;
  length: number | null;
  width: number | null;
  height: number | null;
  brand_id: number | null;
  manufacturer_id: number | null;
  category_id: number;
  discount_id: number | null;
  warranty_id: number | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
  deleted_at: ColumnType<Date, string | undefined> | null;
}

// Brands table interface
export interface BrandTable {
  id: Generated<number>;
  name: string;
  description: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// manufacturer table interface
export interface ManufacturerTable {
  id: Generated<number>;
  name: string;
  description: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Product Variations table interface
export interface ProductVariationTable {
  id: Generated<number>;
  name: string; // E.g., "Size", "Color"
  value: string; // E.g., "Small", "Red"
  price_modifier: number | null; // Incremental price adjustment (e.g., +10 for larger size)
  SKU: string | null; // Specific SKU for the variation
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// product variation mapping table interface
export interface ProductVariationMappingTable {
  id: Generated<number>;
  product_id: number; // Foreign key to product.id
  variation_id: number; // Foreign key to product_variation.id
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// product images  table interface
export interface ProductImagesTable {
  id: Generated<number>;
  product_id: number;
  url: string;
  alt_text: string | null;
  is_primary: boolean;
  order: number;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Category table interface
export interface CategoryTable {
  id: Generated<number>;
  name: string;
  description: string | null;
  parent_id: number | null; // For subcategories, null if it's a main category
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Product Tag table interface
export interface ProductTagTable {
  id: Generated<number>;
  name: string; // Tag name, e.g., "Summer", "New Arrival"
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

//  Product Tag Mapping table interface
export interface ProductTagMappingTable {
  id: Generated<number>;
  product_id: number;
  tag_id: number;
  created_at: ColumnType<Date, string | undefined, never>;
}

// Product Discount table interface
export interface DiscountTable {
  id: Generated<number>;
  description: string | null;
  discount_type: "percentage" | "fixed_amount";
  discount_value: number;
  active: boolean;
  valid_from: Date;
  valid_to: Date | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Warranty table interface
export interface WarrantyTable {
  id: Generated<number>;
  name: string;
  description: string | null;
  duration: number;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Review table interface for product reviews
export interface ProductReviewTable {
  id: Generated<number>;
  user_id: number;
  product_id: number;
  rating: number;
  title: string | null;
  comment: string | null;
  images: JSONColumnType<{ url: string; alt_text: string | null }[]> | null;
  review_status: "pending" | "approved" | "rejected";
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

export type Product = Selectable<ProductTable>;
export type NewProduct = Insertable<ProductTable>;
export type ProductUpdate = Updateable<ProductTable>;
export type Brand = Selectable<BrandTable>;
export type NewBrand = Insertable<BrandTable>;
export type BrandUpdate = Updateable<BrandTable>;
export type Manufacturer = Selectable<ManufacturerTable>;
export type NewManufacturer = Insertable<ManufacturerTable>;
export type ManufacturerUpdate = Updateable<ManufacturerTable>;
export type ProductVariation = Selectable<ProductVariationTable>;
export type NewProductVariation = Insertable<ProductVariationTable>;
export type ProductVariationUpdate = Updateable<ProductVariationTable>;
export type ProductImage = Selectable<ProductImagesTable>;
export type NewProductImage = Insertable<ProductImagesTable>;
export type ProductImageUpdate = Updateable<ProductImagesTable>;
export type Category = Selectable<CategoryTable>;
export type NewCategory = Insertable<CategoryTable>;
export type CategoryUpdate = Updateable<CategoryTable>;
export type ProductTag = Selectable<ProductTagTable>;
export type NewProductTag = Insertable<ProductTagTable>;
export type ProductTagUpdate = Updateable<ProductTagTable>;
export type ProductTagMapping = Selectable<ProductTagMappingTable>;
export type NewProductTagMapping = Insertable<ProductTagMappingTable>;
export type ProductTagMappingUpdate = Updateable<ProductTagMappingTable>;
export type Discount = Selectable<DiscountTable>;
export type NewDiscount = Insertable<DiscountTable>;
export type DiscountUpdate = Updateable<DiscountTable>;
export type Warranty = Selectable<WarrantyTable>;
export type NewWarranty = Insertable<WarrantyTable>;
export type WarrantyUpdate = Updateable<WarrantyTable>;
export type Review = Selectable<ProductReviewTable>;
export type NewReview = Insertable<ProductReviewTable>;
export type ReviewUpdate = Updateable<ProductReviewTable>;

// Cart session table interface
export interface ShoppingSessionTable {
  id: Generated<number>;
  user_id: number;
  total_amount: number;
  expires_at: Date;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// CartItem table interface for items in a cart
export interface CartItemTable {
  id: Generated<number>;
  shopping_session_id: number;
  product_id: number;
  unit_price: number;
  quantity: number;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Order table interface
export interface OrderTable {
  id: Generated<number>;
  user_id: number;
  total_amount: number;
  order_status: "pending" | "completed" | "cancelled";
  order_notes: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// OrderItem table interface
export interface OrderItemTable {
  id: Generated<number>;
  order_id: number;
  product_id: number;
  quantity: number;
  price: number;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Payment table interface
export interface PaymentTable {
  id: Generated<number>;
  order_id: number;
  transaction_id: string;
  amount: number;
  payment_method: "credit_card" | "door_front" | "bank_transfer";
  payment_status: "pending" | "successful" | "failed";
  payment_date: ColumnType<Date, string>;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Shipping table interface
export interface ShippingTable {
  id: Generated<number>;
  order_id: number;
  shipping_method: "standard" | "express";
  shipping_provider: "post" | "tipax" | "iran_payam";
  shipping_address_id: number;
  shipping_status: "pending" | "shipped" | "delivered";
  tracking_number: string;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// Shipping address table interface
export interface ShippingAddressTable {
  id: Generated<number>;
  user_id: number;
  address_line1: string;
  address_line2: string | null;
  city: string;
  state: string;
  zip: string;
  phone: string;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

// refund/return table interface
export interface RefundTable {
  id: Generated<number>;
  order_item_id: number;
  amount: number;
  reason: string;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, Date, Date>;
}

export type ShoppingSession = Selectable<ShoppingSessionTable>;
export type NewShoppingSession = Insertable<ShoppingSessionTable>;
export type ShoppingSessionUpdate = Updateable<ShoppingSessionTable>;
export type CartItem = Selectable<CartItemTable>;
export type NewCartItem = Insertable<CartItemTable>;
export type CartItemUpdate = Updateable<CartItemTable>;
export type Order = Selectable<OrderTable>;
export type NewOrder = Insertable<OrderTable>;
export type OrderUpdate = Updateable<OrderTable>;
export type OrderItem = Selectable<OrderItemTable>;
export type NewOrderItem = Insertable<OrderItemTable>;
export type OrderItemUpdate = Updateable<OrderItemTable>;
export type Payment = Selectable<PaymentTable>;
export type NewPayment = Insertable<PaymentTable>;
export type PaymentUpdate = Updateable<PaymentTable>;
export type Shipping = Selectable<ShippingTable>;
export type NewShipping = Insertable<ShippingTable>;
export type ShippingUpdate = Updateable<ShippingTable>;
export type ShippingAddress = Selectable<ShippingAddressTable>;
export type NewShippingAddress = Insertable<ShippingAddressTable>;
export type ShippingAddressUpdate = Updateable<ShippingAddressTable>;
export type Refund = Selectable<RefundTable>;
export type NewRefund = Insertable<RefundTable>;
export type RefundUpdate = Updateable<RefundTable>;

export interface VerificationRequestTable {
  id: string;
  user_id: number;
  phone_number: string;
  otp: string;
  expires_at: Date;
}

export type VerificationRequest = Selectable<VerificationRequestTable>;
export type NewVerificationRequest = Insertable<VerificationRequestTable>;
export type VerificationRequestUpdate = Updateable<VerificationRequestTable>;
