import type { Metadata } from "next";
import { Header } from "@/components/shop/site-header";
import { Footer } from "@/components/shop/site-footer";
import { SearchModalProvider } from "@/hooks/search-modal-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SearchModalProvider>
      <div className="flex min-h-screen flex-col">
        <Header />
        {children}
        <Footer />
      </div>
    </SearchModalProvider>
  );
}
